### ISSUE TITLE
Error should return error body

### ISSUE THREAD

**Issue by aqidd** [gustavotero7/simple-dpd-mail#1]
currently, send email error will return html options of the email. it should return error body from nodemailer for clarity purposes

https://github.com/gustavotero7/simple-dpd-mail/blob/ab9c3263b107392a007e32881f93866acb59d149/index.js#L136

**Comment by gustavotero7** [comment]
Solved in [f44c2e9](https://github.com/gustavotero7/simple-dpd-mail/commit/f44c2e93932adf836fc939b8449a8b3aa9d6ef01) by @aqidd
